" Status line-nak az airline csomagot használja.
" sudo pacman -S --needed --noconfirm vim-airline vim-airline-themes powerline-fonts

scriptencoding utf-8
set nocompatible
set number
syntax on
filetype indent on
set wildmenu
set wildmode=list:longest
set lazyredraw
set showmatch
set incsearch
set hlsearch
set cursorline
hi CursorLine cterm=NONE ctermbg=darkblue ctermfg=white
set cursorcolumn
hi CursorColumn cterm=NONE ctermbg=darkgray ctermfg=white
au InsertEnter * set nocursorline | set nocursorcolumn | redraw!
au InsertLeave * set cursorline | set cursorcolumn | redraw!
set noexpandtab
set tabstop=4
set softtabstop=4
set noexpandtab
set ignorecase
set ruler
set laststatus=2
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8
set t_Co=256
set mouse=
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme = "dark"
set nolist
set listchars=eol:¬,tab:↹·,trail:⏼,extends:⍈,precedes:⍇,space:␣

" Aktuális dátum idő beszúrása verziónak
iab <expr> __VER strftime("# Verzió: %Y%m%d.%H%M")
"CTRL+n -> set relative line numbers on/off
nmap <C-n> :set invrelativenumber<CR>
"CTRL+l (L) ->set list on/off
nmap <C-l> :set invlist<CR>
"CTRL+f o Fold open
nmap <C-f>o :foldopen<CR>
"CTRL+f c Fold close
nmap <C-f>c :foldclose<CR>
"CTRL+f O Open all folds (max level 999)
nmap <C-F>O :set foldlevel=999<CR>
"CTRL+f C Close all folds
nmap <C-F>C :set foldlevel=0<CR>
